print("********************************************")
print("MADLIBS")
print("********************************************")
substantivo = input("Insira um substantivo: ")
adjetivo = input("Insira um adjetivo: ")
animal = input("Insira um animal: ")
meio_de_transporte = input("Insira um meio de transporte: ")
comida = input("Insira uma comida: ")
print("")
print("Título: Um dia estranho no parque")
print(f"Hoje eu fui ao parque com meu(a) {substantivo}.")
print(f"Lá, nós vimos um(a) {adjetivo} {animal} andando de {meio_de_transporte}!")
print(f"Depois, comemos um pouco de {comida} e rimos muito.")